### ISSUE TITLE
Not compiling on Debian stable with C# (mono)

### ISSUE THREAD

**Issue by singpolyma** [vegardit/haxe-files#3]
`Dir.hx:61: characters 52-89 : Enum<cs.system.Environment_SpecialFolder> has no field UserProfile`

**Comment by sebthom** [comment]
AFAIK `Environment_SpecialFolder.UserProfile` was introduced in .NET4.0 and apparently is available in mono's corlib https://github.com/mono/mono/blob/master/mcs/class/corlib/System/Environment.cs#L93

Can you try using a newer mono version?
