### ISSUE TITLE
Very slow in HL ?

### ISSUE THREAD

**Issue by melMass** [vegardit/haxe-files#4]
Hi,

Thanks for this useful lib, I have a lot of :
`haxe.Utf8 is deprecated. Use UnicodeString instead.`
warnings.

And the same sample in **HL** is taking a LOT more time (x10) than using CPP to Regex match files from a `Dir`'s top-level:

```haxe
Dir.of("/path/to/dir").findFiles("*.prproj");
```

Is this a known issue? And do you plan on updating the library to Haxe 4 release API?

Thanks

**Comment by sebthom** [comment]
Hi Mel, I am currently working on getting rid of the deprecation warnings. HL currently flushes on each line written to stdout, so it could be that the deprecation warnings in the console are slowing down HL. You can try to test with the compiler flag `-D no-deprecation-warnings` and see if it makes a difference.

Seb

**Comment by sebthom** [comment]
I released a new version of the haxe-strings library. Please check if this solves the performance issues you are seeing with haxe-files on HL.

**Comment by melMass** [comment]
For some reason, I missed your previous answer!!
Thanks.
I'll try before tomorow and let you know here ;)

**Comment by sebthom** [comment]
@melMass did you have a chance to try it?

**Comment by melMass** [comment]
Oops thanks for the reminder testing right now on the same project I was referring to !

**Comment by melMass** [comment]
No more unicode warnings but it's still very slow using the command from my first post in a directory with 8 items (3 folders, 5 files). Strange.

Just to be sure `findFiles("*.extension")` is not recursive right ?

**Comment by sebthom** [comment]
`findFiles("*.extension")` is not recursive, `findFiles("**/*.extension")` is recursive

some questions:
- what is your operating system? 
- which minor version of haxe/HL are you using?
- can you check if `FileSystem.readDirectory("<the_path>");` is much slower with HL than with CPP on your workstation?

**Comment by melMass** [comment]
Yes ok as expected.

Currently testing on OSX 10.14
Using:
- Haxe  4.0.2 ( <- Ooops ?)
- HL 1.10.0

**Comment by sebthom** [comment]
do you think you could provide me a small test project that reproduces the issue?
