### ISSUE TITLE
LICENSE.txt is causing crlf errors if used as submodule

### ISSUE THREAD

**Issue by 0b1kn00b** [vegardit/haxe-files#5]
The `autocrlf` in `.gitattributes` causes `License.txt` to be edited (by git) such that `git reset --hard` and `git checkout -- LICENSE.txt` leave `LICENSE.txt` as an unstaged change.

adding `LICENSE.txt binary` to `.gitattributes` fixes this.

note `haxe-strings` and I suppose others have the same things.

**Comment by sebthom** [comment]
Do you only have this issue when used as submodule or also when you clone the repo separately? What OS are you using?

**Comment by 0b1kn00b** [comment]
I'm in linux. If I clone directly, here is the list of files affected.

```
modified:   LICENSE.txt
	modified:   tools/test-cpp.cmd
	modified:   tools/test-cs.cmd
	modified:   tools/test-eval.cmd
	modified:   tools/test-flash.cmd
	modified:   tools/test-hl.cmd
	modified:   tools/test-java.cmd
	modified:   tools/test-jvm.cmd
	modified:   tools/test-lua.cmd
	modified:   tools/test-neko.cmd
	modified:   tools/test-python.cmd
```

**Comment by sebthom** [comment]
I fixed the line endings. please give it a try. I also fixed `haxe-strings`
